### ISSUE TITLE
Include Etherpad core files into the bundle?

### ISSUE THREAD

**Issue by muxator** [storytouch/ep_webpack#11]
Hi,
I am not a Webpack user, but maybe I can give some hints with [this](https://github.com/storytouch/ep_webpack/#next-improvements):

> **Include Etherpad core files into the bundle** (this looks like a hard feature to implement);

In https://github.com/ether/etherpad-lite/pull/3603 I have more or less worked out what needs to be done to bundle etherpad core js files.

My solution there is a POC that uses browserify to create a single `bundle.js`. Migrating to Webpack (or integrating the two approaches) should be within reach.

My goal was getting rid of `require-kernel` (old and unsupported). This broke extension loading, but ep_webpack could probably bring back that functionality.

I guess in its current state ep_webpack is not able to dynamically recompile bundles, and thus we would be limited to a _stop, rebuild, restart_ cycle, but this could be improved in the next steps.

Just an idea with no timeline for now. Let me know if you think it is worth working on it.

**p.s.**: a quick reference for comparing browserify and Webpack can be found here: [browserify for webpack users](https://gist.github.com/substack/68f8d502be42d5cd4942).

**Comment by lpagliari** [comment]
> I guess in its current state ep_webpack is not able to dynamically recompile bundles

Not by itself, you are right. What we currently do is to have a container running webpack on watch mode:
```
  # run watch mode of webpack
  webpack:
    image: node:8.9.0 # same image used by Etherpad containers
    command: bash -c "cd /path/to/etherpad-lite/node_modules/ep_webpack/ && npm run watch -- --config './webpack.config-withCss.js'"
```

Which case would require to recompile bundles? Is it when the user installs a plugin using the admin UI?

I saw that you've opened a draft some days ago, but could not find time to take a look at it yet. Sorry for that, I hope I can do it soon...
